/*
 * Generated by tools/gen_ja_devoice.py from Open JTalk 1.11's
 * njd_set_unvoiced_vowel tables -- do not edit.
 *
 * Rule 5's three candidate classes, projected from upstream's
 * katakana into the (onset, vowel) pair this port uses.  The
 * exclusions are the point: /su/ does not devoice before another
 * s-row mora and /fu hi fi/ not before an h-row one, because that
 * would leave two fricatives with nothing between them.
 *
 * The following mora is matched by PREFIX upstream, so the prefix
 * test is already expanded here and this is plain membership.
 */
#include "ja_devoice_tab.h"

/* the candidate class of each mora, by onset then vowel */
const unsigned char ja_dv_cand[JA_NC][JA_NV] = {
    [JA_C_K    ] = { 0, 3, 3, 0, 0 },
    [JA_C_KY   ] = { 0, 0, 3, 0, 0 },
    [JA_C_T    ] = { 0, 3, 0, 0, 0 },
    [JA_C_P    ] = { 0, 3, 3, 0, 0 },
    [JA_C_PY   ] = { 0, 0, 3, 0, 0 },
    [JA_C_S    ] = { 0, 0, 1, 0, 0 },
    [JA_C_SH   ] = { 0, 3, 3, 0, 0 },
    [JA_C_CH   ] = { 0, 3, 3, 0, 0 },
    [JA_C_TS   ] = { 0, 3, 3, 0, 0 },
    [JA_C_H    ] = { 0, 2, 0, 0, 0 },
    [JA_C_HY   ] = { 0, 0, 3, 0, 0 },
    [JA_C_F    ] = { 0, 2, 2, 0, 0 },
};

/* which classes each mora may follow, as a bitmask */
const unsigned char ja_dv_follow[JA_NC][JA_NV] = {
    [JA_C_K    ] = { 7, 7, 7, 7, 7 },
    [JA_C_KY   ] = { 7, 0, 7, 0, 7 },
    [JA_C_T    ] = { 7, 7, 0, 7, 7 },
    [JA_C_P    ] = { 7, 7, 7, 7, 7 },
    [JA_C_PY   ] = { 7, 0, 7, 0, 7 },
    [JA_C_S    ] = { 6, 0, 6, 6, 6 },
    [JA_C_SH   ] = { 6, 6, 6, 0, 6 },
    [JA_C_CH   ] = { 7, 7, 7, 0, 7 },
    [JA_C_TS   ] = { 7, 7, 7, 7, 7 },
    [JA_C_H    ] = { 5, 5, 0, 5, 5 },
    [JA_C_HY   ] = { 5, 0, 5, 0, 5 },
    [JA_C_F    ] = { 5, 5, 5, 5, 5 },
};
