/*
 * Generated by tools/gen_ja_devoice.py from Open JTalk 1.11's
 * njd_set_unvoiced_vowel tables -- do not edit.
 *
 * Rule 5's three candidate classes, projected from upstream's
 * katakana into the (onset, vowel) pair this port uses.  The
 * exclusions are the point: /su/ does not devoice before another
 * s-row mora and /fu hi fi/ not before an h-row one, because that
 * would leave two fricatives with nothing between them.
 *
 * The following mora is matched by PREFIX upstream, so the prefix
 * test is already expanded here and this is plain membership.
 */
#ifndef JA_DEVOICE_TAB_H
#define JA_DEVOICE_TAB_H

#include "ja.h"

/* 0 = not a devoicing candidate, otherwise its class, 1 to 3. */
extern const unsigned char ja_dv_cand[JA_NC][JA_NV];

/* Bit (class - 1) set: this mora may follow that class. */
extern const unsigned char ja_dv_follow[JA_NC][JA_NV];

#endif
