/*
 * Generated by tools/gen_ja_g2p.py from
 * build/Japanese_test/jp_g2p.py -- do not edit.
 *
 * The adaptation tables: the engine's English phoneme alphabet,
 * what each phoneme becomes in Japanese, and the gaps in the
 * target inventory.  Each was probed against words whose Japanese
 * loanword is not in doubt; the Python carries the reasoning.
 */
#ifndef JA_G2P_TAB_H
#define JA_G2P_TAB_H

/* What a phoneme is, for the adaptation to switch on. */
enum {
    JA_P_CONS = 0,   /* a consonant, with an onset below */
    JA_P_VOWEL,      /* one mora nucleus, maybe long */
    JA_P_DIPH,       /* two morae */
    JA_P_TRIPH,      /* three */
    JA_P_YU,         /* /ju:/, which palatalises its onset */
    JA_P_SPECIAL,    /* NG, the syllabics, the glottal */
    JA_P_DROP        /* a release marker, not a sound */
};

#define JA_P_NONE (-1)
#define JA_P_COUNT 58

/* The engine's one-character symbols -> a phoneme id.  -1 is
 * "not a phoneme", which includes the stress digits and the
 * unit markers. */
extern const signed char ja_g2p_sym[128];

typedef struct {
    const char *name;      /* the two-letter name, for diagnostics */
    unsigned char kind;
    const char *onset;     /* JA_P_CONS: the Japanese onset */
    char        v[3];      /* the vowel letters it becomes */
    unsigned char nv;      /* how many of them */
    unsigned char long_;   /* a chouon follows */
    unsigned char shorten_unstressed;
} ja_g2p_phone;
extern const ja_g2p_phone ja_g2p_tab[JA_P_COUNT];

/* The vowel an onset takes when it has none: オ after /t d/,
 * イ after /tʃ dʒ/, ウ otherwise. */
typedef struct { const char *onset; char v; } ja_g2p_pair;
extern const ja_g2p_pair ja_g2p_epenthetic[];
extern const int ja_g2p_epenthetic_n;
#define JA_G2P_EPENTHETIC_DEFAULT "\165"

/* /ju:/ palatalises rather than adding a glide, and /æ/ does
 * after a velar: キャット, not カット. */
typedef struct { const char *from, *to; } ja_g2p_map;
extern const ja_g2p_map ja_g2p_palatal[];
extern const int ja_g2p_palatal_n;
extern const ja_g2p_map ja_g2p_ae_palatal[];
extern const int ja_g2p_ae_palatal_n;

/* The gaps in the target inventory, and what fills each one.
 * Japanese has no /si zi tu du/ and the kana reader has no
 * ウィ ウェ ウォ チェ シェ ジェ フュ; these are the substitutions,
 * and jp_g2p.self_test is what proves the list is complete. */
typedef struct {
    const char *onset;
    char        v;
    const char *mora[2];
} ja_g2p_repair;
extern const ja_g2p_repair ja_g2p_repair_tab[];
extern const int ja_g2p_repair_n;

/* What geminates before it, after a real short vowel.  /d/ and
 * /g/ do and /b/ does not -- ベッド and バッグ against クラブ --
 * and /s/ does not either: バス, ケース. */
extern const char *const ja_g2p_geminate[];
extern const int ja_g2p_geminate_n;

#endif  /* JA_G2P_TAB_H */
