/*
 * Generated by tools/gen_ja_ojt.py from
 * build/Japanese_test/ojt_tables.py -- do not edit.
 *
 * Open JTalk's rule tables, which are data and not logic.  The
 * chain is: upstream header -> tools/gen_ja_rules.py -> the
 * Python module both front ends were written against -> here.
 * So the C and the Python cannot be reading different tables.
 *
 * Strings are octal-escaped with the text in a comment; see the
 * generator for why.  Open JTalk is BSD 3-clause; see NOTICE.
 */
#ifndef JA_OJT_H
#define JA_OJT_H

/* text2mecab_conv_list: 184 substitutions applied before
 * analysis, ASCII and halfwidth kana TO the fullwidth and
 * composed forms naist-jdic is keyed by.  Longest source
 * first, so the scan takes the longest match. */
typedef struct { const char *src, *dst; } ja_conv;
extern const ja_conv ja_CONV[];
#define ja_CONV_N 184

/* njd_set_unvoiced_vowel_mora_list: the 159 morae the devoicing
 * stage knows, IN UPSTREAM'S ORDER.  That order puts each
 * base's two-character combinations before the bare one, so
 * the first prefix match is the longest one. */
extern const char *const ja_MORA[];
#define ja_MORA_N 159

/* njd_set_pronunciation_list: how a word the dictionary has no
 * reading for gets one.  369 rows, first match wins. */
typedef struct { const char *s, *read; int morae; } ja_pron_row;
extern const ja_pron_row ja_PRON_LIST[];
#define ja_PRON_LIST_N 369

/* njd_set_digit's 50 tables.  Eleven numeral lists, then a
 * class list and a conversion table per counter group; the
 * arity differs per table and the code that walks each one
 * knows it, exactly as upstream does. */
extern const char *const ja_dt_conv_table1b[];
#define ja_dt_conv_table1b_n 4
extern const char *const ja_dt_conv_table1c1[];
#define ja_dt_conv_table1c1_n 8
extern const char *const ja_dt_conv_table1c2[];
#define ja_dt_conv_table1c2_n 12
extern const char *const ja_dt_conv_table1d[];
#define ja_dt_conv_table1d_n 8
extern const char *const ja_dt_conv_table1e[];
#define ja_dt_conv_table1e_n 12
extern const char *const ja_dt_conv_table1f[];
#define ja_dt_conv_table1f_n 16
extern const char *const ja_dt_conv_table1g[];
#define ja_dt_conv_table1g_n 20
extern const char *const ja_dt_conv_table1h[];
#define ja_dt_conv_table1h_n 12
extern const char *const ja_dt_conv_table1i[];
#define ja_dt_conv_table1i_n 12
extern const char *const ja_dt_conv_table1j[];
#define ja_dt_conv_table1j_n 8
extern const char *const ja_dt_conv_table1k[];
#define ja_dt_conv_table1k_n 4
extern const char *const ja_dt_conv_table2b[];
#define ja_dt_conv_table2b_n 20
extern const char *const ja_dt_conv_table2c[];
#define ja_dt_conv_table2c_n 18
extern const char *const ja_dt_conv_table2d[];
#define ja_dt_conv_table2d_n 16
extern const char *const ja_dt_conv_table2e[];
#define ja_dt_conv_table2e_n 6
extern const char *const ja_dt_conv_table2f[];
#define ja_dt_conv_table2f_n 2
extern const char *const ja_dt_conv_table3[];
#define ja_dt_conv_table3_n 8
extern const char *const ja_dt_conv_table4[];
#define ja_dt_conv_table4_n 4
extern const char *const ja_dt_conv_table5[];
#define ja_dt_conv_table5_n 20
extern const char *const ja_dt_conv_table6[];
#define ja_dt_conv_table6_n 20
extern const char *const ja_dt_numeral_list1[];
#define ja_dt_numeral_list1_n 114
extern const char *const ja_dt_numeral_list10[];
#define ja_dt_numeral_list10_n 2
extern const char *const ja_dt_numeral_list11[];
#define ja_dt_numeral_list11_n 12
extern const char *const ja_dt_numeral_list2[];
#define ja_dt_numeral_list2_n 4
extern const char *const ja_dt_numeral_list3[];
#define ja_dt_numeral_list3_n 18
extern const char *const ja_dt_numeral_list4[];
#define ja_dt_numeral_list4_n 12
extern const char *const ja_dt_numeral_list5[];
#define ja_dt_numeral_list5_n 20
extern const char *const ja_dt_numeral_list6[];
#define ja_dt_numeral_list6_n 2
extern const char *const ja_dt_numeral_list7[];
#define ja_dt_numeral_list7_n 8
extern const char *const ja_dt_numeral_list8[];
#define ja_dt_numeral_list8_n 1
extern const char *const ja_dt_numeral_list9[];
#define ja_dt_numeral_list9_n 8
extern const char *const ja_dt_numerative_class1b[];
#define ja_dt_numerative_class1b_n 11
extern const char *const ja_dt_numerative_class1c1[];
#define ja_dt_numerative_class1c1_n 4
extern const char *const ja_dt_numerative_class1c2[];
#define ja_dt_numerative_class1c2_n 4
extern const char *const ja_dt_numerative_class1d[];
#define ja_dt_numerative_class1d_n 2
extern const char *const ja_dt_numerative_class1e[];
#define ja_dt_numerative_class1e_n 1
extern const char *const ja_dt_numerative_class1f[];
#define ja_dt_numerative_class1f_n 0
extern const char *const ja_dt_numerative_class1g[];
#define ja_dt_numerative_class1g_n 142
extern const char *const ja_dt_numerative_class1h[];
#define ja_dt_numerative_class1h_n 135
extern const char *const ja_dt_numerative_class1i[];
#define ja_dt_numerative_class1i_n 35
extern const char *const ja_dt_numerative_class1j[];
#define ja_dt_numerative_class1j_n 5
extern const char *const ja_dt_numerative_class1k[];
#define ja_dt_numerative_class1k_n 32
extern const char *const ja_dt_numerative_class2b[];
#define ja_dt_numerative_class2b_n 22
extern const char *const ja_dt_numerative_class2c[];
#define ja_dt_numerative_class2c_n 10
extern const char *const ja_dt_numerative_class2d[];
#define ja_dt_numerative_class2d_n 0
extern const char *const ja_dt_numerative_class2e[];
#define ja_dt_numerative_class2e_n 8
extern const char *const ja_dt_numerative_class2f[];
#define ja_dt_numerative_class2f_n 1
extern const char *const ja_dt_numerative_class3[];
#define ja_dt_numerative_class3_n 124
extern const char *const ja_dt_semivoiced_sound_symbol_list[];
#define ja_dt_semivoiced_sound_symbol_list_n 10
extern const char *const ja_dt_voiced_sound_symbol_list[];
#define ja_dt_voiced_sound_symbol_list_n 40

/* njd_set_digit's string constants.  Two are spelled
 * NJD_SET_DITIT_ upstream, a typo the extractor takes both
 * spellings of. */
#define JA_DC_BANGOU "\347\225\252\345\217\267"  /* 番号 */
#define JA_DC_COMMA "\357\274\214"  /* ， */
#define JA_DC_FIVE "\344\272\224"  /* 五 */
#define JA_DC_FIVE_AFTER_DP "\343\202\264\343\203\274"  /* ゴー */
#define JA_DC_FIVE_BEFORE_DP "\343\202\264\343\203\274"  /* ゴー */
#define JA_DC_FOUR "\345\233\233"  /* 四 */
#define JA_DC_FUKUSHIKANOU "\345\211\257\350\251\236\345\217\257\350\203\275"  /* 副詞可能 */
#define JA_DC_GATSU "\346\234\210"  /* 月 */
#define JA_DC_HAIHUN1 "\342\200\225"  /* ― */
#define JA_DC_HAIHUN2 "\342\210\222"  /* − */
#define JA_DC_HAIHUN3 "\342\200\220"  /* ‐ */
#define JA_DC_HAIHUN4 "\342\200\224"  /* — */
#define JA_DC_HAIHUN5 "\357\274\215"  /* － */
#define JA_DC_HATSUKA "\344\272\214\345\215\201\346\227\245\054\345\220\215\350\251\236\054\345\211\257\350\251\236\345\217\257\350\203\275\054\052\054\052\054\052\054\052\054\344\272\214\345\215\201\346\227\245\054\343\203\217\343\203\204\343\202\253\054\343\203\217\343\203\204\343\202\253\054\060\057\063\054\052"  /* 二十日,名詞,副詞可能,*,*,*,*,二十日,ハツカ,ハツカ,0/3,* */
#define JA_DC_HATSUKAKAN "\344\272\214\345\215\201\346\227\245\351\226\223\054\345\220\215\350\251\236\054\345\211\257\350\251\236\345\217\257\350\203\275\054\052\054\052\054\052\054\052\054\344\272\214\345\215\201\346\227\245\351\226\223\054\343\203\217\343\203\204\343\202\253\343\202\253\343\203\263\054\343\203\217\343\203\204\343\202\253\343\202\253\343\203\263\054\063\057\065\054\052"  /* 二十日間,名詞,副詞可能,*,*,*,*,二十日間,ハツカカン,ハツカカン,3/5,* */
#define JA_DC_JOSUUSHI "\345\212\251\346\225\260\350\251\236"  /* 助数詞 */
#define JA_DC_JUYOKKA "\345\215\201\345\233\233\346\227\245\054\345\220\215\350\251\236\054\345\211\257\350\251\236\345\217\257\350\203\275\054\052\054\052\054\052\054\052\054\345\215\201\345\233\233\346\227\245\054\343\202\270\343\203\245\343\202\246\343\203\250\343\203\203\343\202\253\054\343\202\270\343\203\245\343\203\274\343\203\250\343\203\203\343\202\253\054\061\057\065\054\052"  /* 十四日,名詞,副詞可能,*,*,*,*,十四日,ジュウヨッカ,ジューヨッカ,1/5,* */
#define JA_DC_JUYOKKAKAN "\345\215\201\345\233\233\346\227\245\351\226\223\054\345\220\215\350\251\236\054\345\211\257\350\251\236\345\217\257\350\203\275\054\052\054\052\054\052\054\052\054\345\215\201\345\233\233\346\227\245\351\226\223\054\343\202\270\343\203\245\343\202\246\343\203\250\343\203\203\343\202\253\343\202\253\343\203\263\054\343\202\270\343\203\245\343\203\274\343\203\250\343\203\203\343\202\253\343\202\253\343\203\263\054\065\057\067\054\052"  /* 十四日間,名詞,副詞可能,*,*,*,*,十四日間,ジュウヨッカカン,ジューヨッカカン,5/7,* */
#define JA_DC_KAKKO1 "\357\274\210"  /* （ */
#define JA_DC_KAKKO2 "\357\274\211"  /* ） */
#define JA_DC_KAZU "\346\225\260"  /* 数 */
#define JA_DC_KIGOU "\350\250\230\345\217\267"  /* 記号 */
#define JA_DC_MEISHI "\345\220\215\350\251\236"  /* 名詞 */
#define JA_DC_NICHI "\346\227\245"  /* 日 */
#define JA_DC_NICHIKAN "\346\227\245\351\226\223"  /* 日間 */
#define JA_DC_NIJU "\344\272\214\345\215\201\054\345\220\215\350\251\236\054\345\211\257\350\251\236\345\217\257\350\203\275\054\052\054\052\054\052\054\052\054\344\272\214\345\215\201\054\343\203\213\343\202\270\343\203\245\343\202\246\054\343\203\213\343\202\270\343\203\245\343\203\274\054\061\057\063\054\052"  /* 二十,名詞,副詞可能,*,*,*,*,二十,ニジュウ,ニジュー,1/3,* */
#define JA_DC_NIN "\344\272\272"  /* 人 */
#define JA_DC_ONE "\344\270\200"  /* 一 */
#define JA_DC_SIX "\345\205\255"  /* 六 */
#define JA_DC_SUUSETSUZOKU "\346\225\260\346\216\245\347\266\232"  /* 数接続 */
#define JA_DC_TEN "\345\215\201"  /* 十 */
#define JA_DC_TEN1 "\357\274\216"  /* ． */
#define JA_DC_TEN2 "\343\203\273"  /* ・ */
#define JA_DC_TEN_FEATURE "\357\274\216\054\345\220\215\350\251\236\054\346\216\245\345\260\276\054\345\212\251\346\225\260\350\251\236\054\052\054\052\054\052\054\357\274\216\054\343\203\206\343\203\263\054\343\203\206\343\203\263\054\060\057\062\054\052\054\055\061"  /* ．,名詞,接尾,助数詞,*,*,*,．,テン,テン,0/2,*,-1 */
#define JA_DC_TSUITACHI "\344\270\200\346\227\245\054\345\220\215\350\251\236\054\345\211\257\350\251\236\345\217\257\350\203\275\054\052\054\052\054\052\054\052\054\344\270\200\346\227\245\054\343\203\204\343\202\244\343\202\277\343\203\201\054\343\203\204\343\202\244\343\202\277\343\203\201\054\064\057\064\054\052"  /* 一日,名詞,副詞可能,*,*,*,*,一日,ツイタチ,ツイタチ,4/4,* */
#define JA_DC_TWO "\344\272\214"  /* 二 */
#define JA_DC_TWO_AFTER_DP "\343\203\213\343\203\274"  /* ニー */
#define JA_DC_TWO_BEFORE_DP "\343\203\213\343\203\274"  /* ニー */
#define JA_DC_YOKKA "\345\233\233\346\227\245\054\345\220\215\350\251\236\054\345\211\257\350\251\236\345\217\257\350\203\275\054\052\054\052\054\052\054\052\054\345\233\233\346\227\245\054\343\203\250\343\203\203\343\202\253\054\343\203\250\343\203\203\343\202\253\054\060\057\063\054\052\054\060"  /* 四日,名詞,副詞可能,*,*,*,*,四日,ヨッカ,ヨッカ,0/3,*,0 */
#define JA_DC_YOKKAKAN "\345\233\233\346\227\245\351\226\223\054\345\220\215\350\251\236\054\345\211\257\350\251\236\345\217\257\350\203\275\054\052\054\052\054\052\054\052\054\345\233\233\346\227\245\351\226\223\054\343\203\250\343\203\203\343\202\253\343\202\253\343\203\263\054\343\203\250\343\203\203\343\202\253\343\202\253\343\203\263\054\063\057\065\054\052\054\060"  /* 四日間,名詞,副詞可能,*,*,*,*,四日間,ヨッカカン,ヨッカカン,3/5,*,0 */
#define JA_DC_ZERO1 "\343\200\207"  /* 〇 */
#define JA_DC_ZERO2 "\357\274\220"  /* ０ */
#define JA_DC_ZERO_AFTER_DP "\343\202\274\343\203\255"  /* ゼロ */
#define JA_DC_ZERO_BEFORE_DP "\343\203\254\343\203\274"  /* レー */

/* njd_set_accent_type's constants, for its digit branch --
 * the accent of 三十, 四百, 何万. */
#define JA_AC_CHOU "\345\205\206"  /* 兆 */
#define JA_AC_GO "\344\272\224"  /* 五 */
#define JA_AC_HACHI "\345\205\253"  /* 八 */
#define JA_AC_HYAKU "\347\231\276"  /* 百 */
#define JA_AC_ICHI "\344\270\200"  /* 一 */
#define JA_AC_IKU "\345\271\276"  /* 幾 */
#define JA_AC_JYUU "\345\215\201"  /* 十 */
#define JA_AC_KAZU "\346\225\260"  /* 数 */
#define JA_AC_KYUU "\344\271\235"  /* 九 */
#define JA_AC_MAN "\344\270\207"  /* 万 */
#define JA_AC_NAN "\344\275\225"  /* 何 */
#define JA_AC_NANA "\344\270\203"  /* 七 */
#define JA_AC_NI "\344\272\214"  /* 二 */
#define JA_AC_OKU "\345\204\204"  /* 億 */
#define JA_AC_ROKU "\345\205\255"  /* 六 */
#define JA_AC_SAN "\344\270\211"  /* 三 */
#define JA_AC_SEN "\345\215\203"  /* 千 */
#define JA_AC_SUU "\346\225\260"  /* 数 */
#define JA_AC_YON "\345\233\233"  /* 四 */

/* the part-of-speech names the eighteen accent-phrase rules test. */
#define JA_AP_DE "\343\201\247"  /* で */
#define JA_AP_DOUSHI "\345\213\225\350\251\236"  /* 動詞 */
#define JA_AP_FUKUSHI "\345\211\257\350\251\236"  /* 副詞 */
#define JA_AP_FUKUSHI_KANOU "\345\211\257\350\251\236\345\217\257\350\203\275"  /* 副詞可能 */
#define JA_AP_HIJIRITSU "\351\235\236\350\207\252\347\253\213"  /* 非自立 */
#define JA_AP_JODOUSHI "\345\212\251\345\213\225\350\251\236"  /* 助動詞 */
#define JA_AP_JOSHI "\345\212\251\350\251\236"  /* 助詞 */
#define JA_AP_KEIYOUDOUSHI_GOKAN "\345\275\242\345\256\271\345\213\225\350\251\236\350\252\236\345\271\271"  /* 形容動詞語幹 */
#define JA_AP_KEIYOUSHI "\345\275\242\345\256\271\350\251\236"  /* 形容詞 */
#define JA_AP_KIGOU "\350\250\230\345\217\267"  /* 記号 */
#define JA_AP_MEI "\345\220\215"  /* 名 */
#define JA_AP_MEISHI "\345\220\215\350\251\236"  /* 名詞 */
#define JA_AP_RENTAISHI "\351\200\243\344\275\223\350\251\236"  /* 連体詞 */
#define JA_AP_RENYOU "\351\200\243\347\224\250"  /* 連用 */
#define JA_AP_SAHEN_SETSUZOKU "\343\202\265\345\244\211\346\216\245\347\266\232"  /* サ変接続 */
#define JA_AP_SEI "\345\247\223"  /* 姓 */
#define JA_AP_SETSUBI "\346\216\245\345\260\276"  /* 接尾 */
#define JA_AP_SETSUZOKUJOSHI "\346\216\245\347\266\232\345\212\251\350\251\236"  /* 接続助詞 */
#define JA_AP_SETSUZOKUSHI "\346\216\245\347\266\232\350\251\236"  /* 接続詞 */
#define JA_AP_SETTOUSHI "\346\216\245\351\240\255\350\251\236"  /* 接頭詞 */
#define JA_AP_TE "\343\201\246"  /* て */

/* what the devoicing stage tests: four parts of speech, the two
 * whole-word symbols, the devoicing mark, and the kana of the
 * masu/desu and shi look-aheads. */
#define JA_UV_CHOUON "\343\203\274"  /* ー */
#define JA_UV_DE "\343\203\207"  /* デ */
#define JA_UV_DOUSHI "\345\213\225\350\251\236"  /* 動詞 */
#define JA_UV_FILLER "\343\203\225\343\202\243\343\203\251\343\203\274"  /* フィラー */
#define JA_UV_JODOUSHI "\345\212\251\345\213\225\350\251\236"  /* 助動詞 */
#define JA_UV_JOSHI "\345\212\251\350\251\236"  /* 助詞 */
#define JA_UV_KANDOUSHI "\346\204\237\345\213\225\350\251\236"  /* 感動詞 */
#define JA_UV_MA "\343\203\236"  /* マ */
#define JA_UV_QUESTION "\357\274\237"  /* ？ */
#define JA_UV_QUOTATION "\342\200\231"  /* ’ */
#define JA_UV_SHI "\343\202\267"  /* シ */
#define JA_UV_SU "\343\202\271"  /* ス */
#define JA_UV_TOUTEN "\343\200\201"  /* 、 */

/* njd_set_pronunciation's own constants. */
#define JA_PR_CHOUON "\343\203\274"  /* ー */
#define JA_PR_DESU_PRON "\343\203\207\343\202\271"  /* デス */
#define JA_PR_DESU_STR "\343\201\247\343\201\231"  /* です */
#define JA_PR_DOUSHI "\345\213\225\350\251\236"  /* 動詞 */
#define JA_PR_FILLER "\343\203\225\343\202\243\343\203\251\343\203\274"  /* フィラー */
#define JA_PR_JODOUSHI "\345\212\251\345\213\225\350\251\236"  /* 助動詞 */
#define JA_PR_KAZU "\346\225\260"  /* 数 */
#define JA_PR_KIGOU "\350\250\230\345\217\267"  /* 記号 */
#define JA_PR_MASU_PRON "\343\203\236\343\202\271"  /* マス */
#define JA_PR_MASU_STR "\343\201\276\343\201\231"  /* ます */
#define JA_PR_QUESTION "\357\274\237"  /* ？ */
#define JA_PR_TOUTEN "\343\200\201"  /* 、 */
#define JA_PR_U "\343\202\246"  /* ウ */

/* The three devoicing candidate classes, each with the
 * following-mora list it devoices before.  Upstream's own
 * tables: /su/ does not devoice before another s-row mora and
 * /fu hi fi/ not before an h-row one, because that would leave
 * two fricatives with nothing between them. */
extern const char *const ja_uv_candidate_list1[];
#define ja_uv_candidate_list1_n 2
extern const char *const ja_uv_candidate_list2[];
#define ja_uv_candidate_list2_n 3
extern const char *const ja_uv_candidate_list3[];
#define ja_uv_candidate_list3_n 16
extern const char *const ja_uv_next_mora_list1[];
#define ja_uv_next_mora_list1_n 20
extern const char *const ja_uv_next_mora_list2[];
#define ja_uv_next_mora_list2_n 20
extern const char *const ja_uv_next_mora_list3[];
#define ja_uv_next_mora_list3_n 25

/* OURS, not Open JTalk's, emitted from the Python that
 * defines them.  Open JTalk folds every punctuation mark into
 * one pause symbol; this front end keeps the strong break,
 * because its prosody grades the boundary and has nowhere
 * later to recover the distinction.  See declared_pause in
 * tools/ja_stage_parity.py. */
#define JA_OUR_PERIOD "\343\200\202"  /* 。 */
extern const char *const ja_BREAK_STRONG[];
#define ja_BREAK_STRONG_n 4
extern const char *const ja_BREAK_WEAK[];
#define ja_BREAK_WEAK_n 8
extern const char *const ja_QUESTION_FORMS[];
#define ja_QUESTION_FORMS_n 2

/* A mora the kana reader has no symbol for, spelled out
 * rather than dropped.  Read jp_front._SPELL_OUT for what each
 * one costs; the short version is that a bare small vowel
 * becomes its full-size vowel and ヮ becomes /wa/, which is
 * wrong about the consonant and right about the mora count. */
typedef struct { const char *kata, *romaji; } ja_spell;
extern const ja_spell ja_SPELL_OUT[];
#define ja_SPELL_OUT_N 9

#endif  /* JA_OJT_H */
