GenericExecuteSynth \
"retro-tts --persistent --engine amiganarrator --rate $RATE --pitch $PITCH --voice '$VOICE' --text \'$DATA\'"

GenericCmdDependency "retro-tts"
GenericSoundIconFolder "/usr/share/sounds/sound-icons/"
AddVoice "en" "MALE1" "Male Natural"
AddVoice "en" "MALE1" "Male Robotic"
AddVoice "en" "MALE1" "Female Natural"
AddVoice "en" "MALE1" "Female Robotic"
DefaultVoice "Male Natural"
GenericDefaultCharset "utf-8"
GenericRateForceInteger 1
GenericPitchForceInteger 1
GenericRateAdd 50
GenericPitchAdd 50
GenericRateMultiply 50
GenericPitchMultiply 50
