GenericExecuteSynth \
"retro-tts --persistent --engine bestspeech --rate $RATE --pitch $PITCH --voice '$VOICE' --text \'$DATA\'"
GenericCmdDependency "retro-tts"
GenericSoundIconFolder "/usr/share/sounds/sound-icons/"
AddVoice "en" "MALE1" "fred"
AddVoice "en" "MALE1" "sara"
AddVoice "en" "MALE1" "hary"
AddVoice "en" "MALE1" "wendy"
AddVoice "en" "MALE1" "dexter"
AddVoice "en" "MALE1" "alien"
AddVoice "en" "MALE1" "kit"
AddVoice "en" "MALE1" "bruno"
AddVoice "en" "MALE1" "ghost"
AddVoice "en" "MALE1" "peeper"
AddVoice "en" "MALE1" "dracula"
AddVoice "en" "MALE1" "granny"
AddVoice "en" "MALE1" "martha"
AddVoice "en" "MALE1" "tim"
AddVoice "en" "MALE1" "English - fred"
AddVoice "nl" "MALE1" "Dutch - fred"
AddVoice "fr" "MALE1" "French - fred"
AddVoice "de" "MALE1" "German - fred"
AddVoice "el" "MALE1" "Greek - fred"
AddVoice "he" "MALE1" "Hebrew - fred"
AddVoice "it" "MALE1" "Italian - fred"
AddVoice "ja" "MALE1" "Japanese - fred"
AddVoice "pl" "MALE1" "Polish - fred"
AddVoice "pt" "MALE1" "Portuguese - fred"
AddVoice "ru" "MALE1" "Russian - fred"
AddVoice "es" "MALE1" "Spanish - fred"
DefaultVoice "fred"
GenericDefaultCharset "utf-8"
GenericRateForceInteger 1
GenericPitchForceInteger 1
GenericRateAdd 50
GenericPitchAdd 50
GenericRateMultiply 50
GenericPitchMultiply 0.5
