GenericExecuteSynth \
"retro-tts --persistent --engine doubletalkpc --rate $RATE --pitch $PITCH --voice '$VOICE' --text \'$DATA\'"

GenericCmdDependency "retro-tts"
GenericSoundIconFolder "/usr/share/sounds/sound-icons/"
AddVoice "en" "MALE1" "Perfect Paul"
AddVoice "en" "MALE1" "Vader"
AddVoice "en" "MALE1" "Big Bob"
AddVoice "en" "MALE1" "Precise Pete"
AddVoice "en" "MALE1" "Ricochet"
AddVoice "en" "MALE1" "Biff"
AddVoice "en" "MALE1" "Skip"
AddVoice "en" "MALE1" "Robo Robert"
DefaultVoice "Perfect Paul"
GenericDefaultCharset "utf-8"
GenericRateForceInteger 1
GenericPitchForceInteger 1
GenericRateAdd 50
GenericPitchAdd 50
GenericRateMultiply 50
GenericPitchMultiply 50
