GenericExecuteSynth \
"retro-tts --persistent --engine echotalk --rate $RATE --pitch $PITCH --volume $VOLUME --voice '$VOICE' --text \'$DATA\'"
GenericCmdDependency "retro-tts"
GenericSoundIconFolder "/usr/share/sounds/sound-icons/"
AddVoice "en" "MALE1" "Textalker 3.1.3"
AddVoice "en" "MALE1" "Textalker 1.3"
DefaultVoice "Textalker 3.1.3"
GenericDefaultCharset "utf-8"
GenericRateForceInteger 1
GenericPitchForceInteger 1
GenericVolumeForceInteger 1
GenericRateAdd 50
GenericPitchAdd 60
GenericVolumeAdd 50
GenericRateMultiply 50
GenericPitchMultiply 50
GenericVolumeMultiply 50
