GenericExecuteSynth \
"retro-tts --persistent --engine lhtts --rate $RATE --pitch $PITCH --volume $VOLUME --voice '$VOICE' --text \'$DATA\'"
GenericCmdDependency "retro-tts"
GenericSoundIconFolder "/usr/share/sounds/sound-icons/"
AddVoice "en-US" "MALE1" "Michael (American English)"
AddVoice "en-US" "FEMALE1" "Michelle (American English)"
AddVoice "en-US" "FEMALE1" "Julia (American English)"
AddVoice "en-US" "FEMALE1" "Wanda (American English)"
AddVoice "en-US" "MALE1" "Alex (American English)"
AddVoice "en-US" "MALE1" "Melvin (American English)"
AddVoice "en-US" "MALE1" "Grandpa Amos (American English)"
AddVoice "en-US" "MALE1" "Biff (American English)"
AddVoice "en-US" "MALE1" "Deep Douglas (American English)"
AddVoice "en-US" "MALE1" "Eager Eddie (American English)"
AddVoice "en-US" "MALE1" "Sidney (American English)"
AddVoice "en-US" "MALE1" "Peter (American English)"
AddVoice "en-GB" "MALE1" "Peter (British English)"
AddVoice "en-GB" "FEMALE1" "Carol (British English)"
AddVoice "fr" "MALE1" "Pierre (French)"
AddVoice "fr" "FEMALE1" "Veronique (French)"
AddVoice "de" "MALE1" "Stefan (German)"
AddVoice "de" "FEMALE1" "Anna (German)"
AddVoice "it" "MALE1" "Stefano (Italian)"
AddVoice "it" "FEMALE1" "Barbara (Italian)"
AddVoice "es" "MALE1" "Julio (Spanish)"
AddVoice "es" "FEMALE1" "Carmen (Spanish)"
AddVoice "nl" "MALE1" "Alexander (Dutch)"
AddVoice "nl" "FEMALE1" "Linda (Dutch)"
AddVoice "ru" "MALE1" "Boris (Russian)"
AddVoice "ru" "FEMALE1" "Svetlana (Russian)"
AddVoice "ko" "MALE1" "Jun-Ho (Korean)"
AddVoice "ko" "FEMALE1" "Shin-Ah (Korean)"
DefaultVoice "Michael (American English)"
GenericDefaultCharset "utf-8"
GenericRateForceInteger 1
GenericPitchForceInteger 1
GenericVolumeForceInteger 1
GenericRateAdd 50
GenericPitchAdd 50
GenericVolumeAdd 50
GenericRateMultiply 50
GenericPitchMultiply 50
GenericVolumeMultiply 50
