GenericExecuteSynth \
"retro-tts --persistent --engine lionspeech --voice \'$VOICE\' --rate $RATE --pitch $PITCH --volume $VOLUME --text \'$DATA\'"
GenericCmdDependency "retro-tts"
GenericSoundIconFolder "/usr/share/sounds/sound-icons/"
AddVoice "en" "MALE1" "Alex"
AddVoice "en" "MALE1" "Vicki"
AddVoice "en" "MALE1" "Fred"
AddVoice "en" "MALE1" "Bruce"
AddVoice "en" "MALE1" "Victoria"
AddVoice "en" "MALE1" "Agnes"
AddVoice "en" "MALE1" "Junior"
AddVoice "en" "MALE1" "Princess"
AddVoice "en" "MALE1" "Ralph"
AddVoice "en" "MALE1" "Albert"
AddVoice "en" "MALE1" "BadNews"
AddVoice "en" "MALE1" "Bahh"
AddVoice "en" "MALE1" "Bells"
AddVoice "en" "MALE1" "Boing"
AddVoice "en" "MALE1" "Bubbles"
AddVoice "en" "MALE1" "Cellos"
AddVoice "en" "MALE1" "Deranged"
AddVoice "en" "MALE1" "GoodNews"
AddVoice "en" "MALE1" "Hysterical"
AddVoice "en" "MALE1" "Kathy"
AddVoice "en" "MALE1" "Organ"
AddVoice "en" "MALE1" "Trinoids"
AddVoice "en" "MALE1" "Whisper"
AddVoice "en" "MALE1" "Zarvox"
DefaultVoice "Alex"
GenericDefaultCharset "utf-8"
GenericRateForceInteger 1
GenericPitchForceInteger 1
GenericVolumeForceInteger 1
GenericRateAdd 50
GenericPitchAdd 50
GenericVolumeAdd 90
GenericRateMultiply 50
GenericPitchMultiply 50
GenericVolumeMultiply 90
