GenericExecuteSynth \
"retro-tts --persistent --engine monologue --rate $RATE --pitch $PITCH --voice '$VOICE' --text \'$DATA\'"

GenericCmdDependency "retro-tts"
GenericSoundIconFolder "/usr/share/sounds/sound-icons/"
AddVoice "en" "MALE1" "Monologue (ProVoice 22 kHz, male)"
AddVoice "en" "MALE1" "Monologue (ProVoice 11 kHz, male)"
DefaultVoice "Monologue (ProVoice 22 kHz, male)"
GenericDefaultCharset "utf-8"
GenericRateForceInteger 1
GenericPitchForceInteger 1
GenericRateAdd 50
GenericPitchAdd 50
GenericRateMultiply 50
GenericPitchMultiply 50
