GenericExecuteSynth \
"retro-tts --persistent --engine mssam --rate $RATE --pitch $PITCH --volume $VOLUME --voice '$VOICE' --text \\'$DATA\\'"

GenericCmdDependency "retro-tts"
GenericSoundIconFolder "/usr/share/sounds/sound-icons/"
AddVoice "en" "MALE1" "Sam"
AddVoice "en" "MALE1" "Mike"
AddVoice "en" "FEMALE1" "Mary"
DefaultVoice "Sam"
GenericDefaultCharset "utf-8"
GenericRateForceInteger 1
GenericPitchForceInteger 1
GenericVolumeForceInteger 1
GenericRateAdd 50
GenericPitchAdd 50
GenericVolumeAdd 50
GenericRateMultiply 50
GenericPitchMultiply 50
GenericVolumeMultiply 50
