GenericExecuteSynth \
"retro-tts --persistent --engine onecore --rate $RATE --volume $VOLUME --voice '$VOICE' --text \\'$DATA\\'"

GenericCmdDependency "retro-tts"
GenericSoundIconFolder "/usr/share/sounds/sound-icons/"
AddVoice "en" "MALE1" "David"
AddVoice "en" "FEMALE1" "Zira"
AddVoice "en" "MALE1" "Mark"
DefaultVoice "David"
GenericDefaultCharset "utf-8"
GenericRateForceInteger 1
GenericVolumeForceInteger 1
GenericRateAdd 50
GenericVolumeAdd 50
GenericRateMultiply 50
GenericVolumeMultiply 50
