GenericExecuteSynth \
"retro-tts --persistent --engine outspoken --rate $RATE --pitch $PITCH --volume $VOLUME --voice '$VOICE' --text \'$DATA\'"
GenericCmdDependency "retro-tts"
GenericSoundIconFolder "/usr/share/sounds/sound-icons/"
AddVoice "en" "MALE1" "Male (MacinTalk 1)"
AddVoice "en" "MALE1" "Female (MacinTalk 1)"
AddVoice "en" "MALE1" "Ben (MacinTalk 2)"
AddVoice "en" "MALE1" "Boris (MacinTalk 2)"
AddVoice "en" "MALE1" "Brenda (MacinTalk 2)"
AddVoice "en" "MALE1" "Mariel (MacinTalk 2)"
AddVoice "en" "MALE1" "Marvin (MacinTalk 2)"
AddVoice "en" "MALE1" "Mr. Hughes (MacinTalk 2)"
AddVoice "en" "MALE1" "Otis (MacinTalk 2)"
AddVoice "en" "MALE1" "RoboVox (MacinTalk 2)"
AddVoice "en" "MALE1" "Votron (MacinTalk 2)"
AddVoice "en" "MALE1" "Xero (MacinTalk 2)"
AddVoice "en" "MALE1" "Albert (MacinTalk 3)"
AddVoice "en" "MALE1" "Bad News (MacinTalk 3)"
AddVoice "en" "MALE1" "Bahh (MacinTalk 3)"
AddVoice "en" "MALE1" "Bells (MacinTalk 3)"
AddVoice "en" "MALE1" "Boing (MacinTalk 3)"
AddVoice "en" "MALE1" "Bubbles (MacinTalk 3)"
AddVoice "en" "MALE1" "Cellos (MacinTalk 3)"
AddVoice "en" "MALE1" "Deranged (MacinTalk 3)"
AddVoice "en" "MALE1" "Fred (MacinTalk 3)"
AddVoice "en" "MALE1" "Good News (MacinTalk 3)"
AddVoice "en" "MALE1" "Hysterical (MacinTalk 3)"
AddVoice "en" "MALE1" "Junior (MacinTalk 3)"
AddVoice "en" "MALE1" "Kathy (MacinTalk 3)"
AddVoice "en" "MALE1" "Pipe Organ (MacinTalk 3)"
AddVoice "en" "MALE1" "Princess (MacinTalk 3)"
AddVoice "en" "MALE1" "Ralph (MacinTalk 3)"
AddVoice "en" "MALE1" "Trinoids (MacinTalk 3)"
AddVoice "en" "MALE1" "Whisper (MacinTalk 3)"
AddVoice "en" "MALE1" "Zarvox (MacinTalk 3)"
AddVoice "en" "MALE1" "Agnes (MacinTalk Pro)"
AddVoice "en" "MALE1" "Bruce (MacinTalk Pro)"
AddVoice "en" "MALE1" "Victoria (MacinTalk Pro)"
DefaultVoice "Male (MacinTalk 1)"
GenericDefaultCharset "utf-8"
GenericRateForceInteger 1
GenericPitchForceInteger 1
GenericVolumeForceInteger 1
GenericRateAdd 50
GenericPitchAdd 50
GenericVolumeAdd 50
GenericRateMultiply 50
GenericPitchMultiply 50
GenericVolumeMultiply 50
