GenericExecuteSynth \
"retro-tts --persistent --engine sam --rate $RATE --pitch $PITCH --voice '$VOICE' --text \'$DATA\'"

GenericCmdDependency "retro-tts"
GenericSoundIconFolder "/usr/share/sounds/sound-icons/"
AddVoice "en" "MALE1" "Sam"
AddVoice "en" "MALE1" "Elf"
AddVoice "en" "MALE1" "Little Robot"
AddVoice "en" "MALE1" "Stuffy Guy"
AddVoice "en" "MALE1" "Little Old Lady"
AddVoice "en" "MALE1" "Extra Terrestrial"
DefaultVoice "Sam"
GenericDefaultCharset "utf-8"
GenericRateForceInteger 1
GenericPitchForceInteger 1
GenericRateAdd 50
GenericPitchAdd 50
GenericRateMultiply 50
GenericPitchMultiply 50
