GenericExecuteSynth \
"retro-tts --persistent --engine softvoice --rate $RATE --pitch $PITCH --voice '$VOICE' --text \'$DATA\'"
GenericCmdDependency "retro-tts"
GenericSoundIconFolder "/usr/share/sounds/sound-icons/"
AddVoice "en" "MALE1" "Male"
AddVoice "en" "MALE1" "Female"
AddVoice "en" "MALE1" "Large Male"
AddVoice "en" "MALE1" "Child"
AddVoice "en" "MALE1" "Giant Male"
AddVoice "en" "MALE1" "Mellow Female"
AddVoice "en" "MALE1" "Mellow Male"
AddVoice "en" "MALE1" "Crisp Male"
AddVoice "en" "MALE1" "The Fly"
AddVoice "en" "MALE1" "Robotoid"
AddVoice "en" "MALE1" "Martian"
AddVoice "en" "MALE1" "Colossus"
AddVoice "en" "MALE1" "Fast Fred"
AddVoice "en" "MALE1" "Old Woman"
AddVoice "en" "MALE1" "Munchkin"
AddVoice "en" "MALE1" "Troll"
AddVoice "en" "MALE1" "Nerd"
AddVoice "en" "MALE1" "Milktoast"
AddVoice "en" "MALE1" "Tipsy"
AddVoice "en" "MALE1" "Choirboy"
AddVoice "es" "MALE1" "Spanish Male"
AddVoice "es" "MALE1" "Spanish Female"
DefaultVoice "Male"
GenericDefaultCharset "utf-8"
GenericRateForceInteger 1
GenericPitchForceInteger 1
GenericRateAdd 50
GenericPitchAdd 50
GenericRateMultiply 50
GenericPitchMultiply 50
