GenericExecuteSynth \
"retro-tts --persistent --engine truevoice --rate $RATE --pitch $PITCH --volume $VOLUME --voice '$VOICE' --text \'$DATA\'"
GenericCmdDependency "retro-tts"
GenericSoundIconFolder "/usr/share/sounds/sound-icons/"
AddVoice "en" "MALE1" "Peter"
AddVoice "en" "MALE1" "Sidney"
AddVoice "en" "MALE1" "Eager Eddie"
AddVoice "en" "MALE1" "Deep Douglas"
AddVoice "en" "MALE1" "Biff"
AddVoice "en" "MALE1" "Grandpa Amos"
AddVoice "en" "MALE1" "Melvin"
AddVoice "en" "MALE1" "Alex"
AddVoice "en" "FEMALE1" "Wanda"
AddVoice "en" "FEMALE1" "Julia"
DefaultVoice "Peter"
GenericDefaultCharset "utf-8"
GenericRateForceInteger 1
GenericPitchForceInteger 1
GenericVolumeForceInteger 1
GenericRateAdd 50
GenericPitchAdd 50
GenericVolumeAdd 50
GenericRateMultiply 50
GenericPitchMultiply 50
GenericVolumeMultiply 50
