GenericExecuteSynth \
"retro-tts --persistent --engine wintalker --rate $RATE --pitch $PITCH --voice '$VOICE' --text \'$DATA\'"
GenericCmdDependency "retro-tts"
GenericSoundIconFolder "/usr/share/sounds/sound-icons/"
AddVoice "en" "MALE1" "Fred"
AddVoice "en" "MALE1" "Kathy"
AddVoice "en" "MALE1" "Princess"
AddVoice "en" "MALE1" "Junior"
AddVoice "en" "MALE1" "Ralph"
AddVoice "en" "MALE1" "Whisper"
AddVoice "en" "MALE1" "Zarvox"
AddVoice "en" "MALE1" "Trinoids"
AddVoice "en" "MALE1" "Bubbles"
AddVoice "en" "MALE1" "Boing"
AddVoice "en" "MALE1" "Bells"
AddVoice "en" "MALE1" "Hysterical"
AddVoice "en" "MALE1" "Deranged"
AddVoice "en" "MALE1" "Good News"
AddVoice "en" "MALE1" "Bad News"
AddVoice "en" "MALE1" "Pipe Organ"
AddVoice "en" "MALE1" "Cellos"
DefaultVoice "Fred"
GenericDefaultCharset "utf-8"
GenericRateForceInteger 1
GenericPitchForceInteger 1
GenericRateAdd 50
GenericPitchAdd 50
GenericRateMultiply 50
GenericPitchMultiply 50
