/* zf1_morph_tab.h - generated by tools/gen_morph_tab.py from MSTTSLoc_OneCore.dll (CEnMorph tables). */
static const struct { int rule; const char *suffix; int len; } zf1_morph_suffix[33] = {
    {5, "er", 2},
    {6, "est", 3},
    {2, "ing", 3},
    {14, "able", 4},
    {14, "ible", 4},
    {24, "ably", 4},
    {24, "ibly", 4},
    {26, "ically", 6},
    {28, "ily", 3},
    {13, "ly", 2},
    {11, "y", 1},
    {8, "ment", 4},
    {7, "or", 2},
    {15, "ness", 4},
    {10, "less", 4},
    {30, "icize", 5},
    {17, "ize", 3},
    {18, "iz", 2},
    {29, "icism", 5},
    {31, "icise", 5},
    {16, "ism", 3},
    {1, "ed", 2},
    {3, "'s", 2},
    {0, "s", 1},
    {4, "'", 1},
    {9, "age", 3},
    {19, "hood", 4},
    {20, "ful", 3},
    {21, "like", 4},
    {22, "wise", 4},
    {23, "ish", 3},
    {25, "ship", 4},
    {27, "some", 4},
};
static const struct { const char *phones; int n; const char *from[4], *to[4]; unsigned flags; } zf1_morph_rule[32] = {
    {" s", 2, {"verb", "noun", NULL, NULL}, {"verb", "noun", NULL, NULL}, 0x0},
    {" d", 3, {"verb", "verb", "verb", NULL}, {"verb", "adj", "verbpastp", NULL}, 0x7},
    {" IH NG", 3, {"verb", "verb", "verb", NULL}, {"verbing", "adj", "noun", NULL}, 0x5},
    {" s", 1, {"noun", NULL, NULL, NULL}, {"noun", NULL, NULL, NULL}, 0x0},
    {"  ", 1, {"noun", NULL, NULL, NULL}, {"noun", NULL, NULL, NULL}, 0x0},
    {" ER", 4, {"verb", "adj", "adv", "adj"}, {"noun", "adj", "adv", "adv"}, 0x7},
    {" AX s t", 3, {"adj", "adv", "adj", NULL}, {"adj", "adv", "adv", NULL}, 0x7},
    {" ER", 1, {"verb", NULL, NULL, NULL}, {"noun", NULL, NULL, NULL}, 0x5},
    {" m AX n t", 1, {"verb", NULL, NULL, NULL}, {"noun", NULL, NULL, NULL}, 0x2},
    {" IH JH", 1, {"verb", NULL, NULL, NULL}, {"noun", NULL, NULL, NULL}, 0x5},
    {" l IH s", 1, {"noun", NULL, NULL, NULL}, {"adj", NULL, NULL, NULL}, 0x2},
    {" IY", 2, {"noun", "adj", NULL, NULL}, {"adj", "adv", NULL, NULL}, 0x5},
    {" AX d l IY", 2, {"verb", "verb", NULL, NULL}, {"adj", "adv", NULL, NULL}, 0x7},
    {" l IY", 2, {"noun", "adj", NULL, NULL}, {"adj", "adv", NULL, NULL}, 0x10},
    {" AX - b AX l", 2, {"verb", "noun", NULL, NULL}, {"adj", "adj", NULL, NULL}, 0x7},
    {" n IH s", 1, {"adj", NULL, NULL, NULL}, {"noun", NULL, NULL, NULL}, 0x2},
    {" IH z AX m", 2, {"adj", "noun", NULL, NULL}, {"noun", "noun", NULL, NULL}, 0x1},
    {" AY z", 2, {"noun", "adj", NULL, NULL}, {"verb", "verb", NULL, NULL}, 0x1},
    {" AY z", 2, {"noun", "adj", NULL, NULL}, {"verb", "verb", NULL, NULL}, 0x1},
    {" h UH d", 1, {"noun", NULL, NULL, NULL}, {"noun", NULL, NULL, NULL}, 0x0},
    {" f AX l", 2, {"noun", "verb", NULL, NULL}, {"adj", "adj", NULL, NULL}, 0x0},
    {" l AY k", 1, {"noun", NULL, NULL, NULL}, {"adj", NULL, NULL, NULL}, 0x0},
    {" w AY z", 1, {"noun", NULL, NULL, NULL}, {"adj", NULL, NULL, NULL}, 0x2},
    {" IH SH", 1, {"noun", NULL, NULL, NULL}, {"adj", NULL, NULL, NULL}, 0x5},
    {" AX - b l IY", 2, {"verb", "noun", NULL, NULL}, {"adv", "adv", NULL, NULL}, 0x7},
    {" SH IH 2 p", 1, {"noun", NULL, NULL, NULL}, {"noun", NULL, NULL, NULL}, 0x0},
    {" L IY", 1, {"adj", NULL, NULL, NULL}, {"adv", NULL, NULL, NULL}, 0x0},
    {" S AX M", 1, {"noun", NULL, NULL, NULL}, {"adj", NULL, NULL, NULL}, 0x2},
    {" AX L IY", 1, {"noun", NULL, NULL, NULL}, {"adv", NULL, NULL, NULL}, 0xc},
    {" IH z AX m", 2, {"adj", "noun", NULL, NULL}, {"noun", "noun", NULL, NULL}, 0x1},
    {" AY z", 2, {"noun", "adj", NULL, NULL}, {"verb", "verb", NULL, NULL}, 0x1},
    {" AY z", 2, {"noun", "adj", NULL, NULL}, {"verb", "verb", NULL, NULL}, 0x1},
};
/* pron table (index = byte offset / 8 - 1: +8 .. +0x88) */
static const char *const zf1_morph_ptab[17] = {
    " AX l",  /* +0x8 */
    " AX z",  /* +0x10 */
    " AX l er",  /* +0x18 */
    " l er",  /* +0x20 */
    " s",  /* +0x28 */
    " z",  /* +0x30 */
    " d",  /* +0x38 */
    " AX d",  /* +0x40 */
    " IH d",  /* +0x48 */
    " t",  /* +0x50 */
    " r",  /* +0x58 */
    " v",  /* +0x60 */
    " w",  /* +0x68 */
    " dh",  /* +0x70 */
    " jh",  /* +0x78 */
    " IY",  /* +0x80 */
    " l",  /* +0x88 */
};
