/*
 * The two places the original's output depended on the host's libm.
 *
 * SAPI volume and the ESC[..a attenuation command were a pow() and a
 * log10() whose results are immediately truncated to a small integer, so
 * what reaches the audio is a step function with a few dozen steps.  A
 * library that rounds the last bit differently -- another platform, another
 * compiler, SSE2 instead of the x87 the 32-bit build uses, where the
 * multiply carries 80 bits of intermediate precision -- would move a step
 * boundary by one and change the output, in a way that would look like a
 * decompilation bug.  The steps are tabulated here instead.
 *
 * The tables were generated by evaluating the original expressions with the
 * standalone build's own flags and libm, and checked against those
 * expressions over every input: all 4,294,967,216 volumes from 0x50 to
 * 0xffffffff and all 256 attenuation arguments, exactly equal throughout.
 */
#include "engine.h"

static const uint16_t g_vol_of_atten[256] = {
    65535, 52056, 41349, 32845, 26089, 20723, 16461, 13075, 10386, 8250, 6553, 5205,
    4134, 3284, 2608, 2072, 1646, 1307, 1038, 825, 655, 520, 413, 328,
    260, 207, 164, 130, 103, 82, 65, 52, 41, 32, 26, 20,
    16, 13, 10, 8, 6, 5, 4, 3, 2, 2, 1, 1,
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0
};

static const uint32_t g_atten_bound[64] = {
    0xffffffffu, 0xf676c58du, 0xc3c5f567u, 0x9b821c0eu, 0x7b864b48u, 0x621e7b24u,
    0x4df05196u, 0x3de8b0a9u, 0x312d0fe0u, 0x270fd8efu, 0x1f072940u, 0x18a57a27u,
    0x1393cbbdu, 0x0f8d02ceu, 0x0c5a3abau, 0x09cfd91du, 0x07cb3b5bu, 0x0630de77u,
    0x04eae7fcu, 0x03e7fc17u, 0x031a50ecu, 0x0276f29du, 0x01f52df9u, 0x018e19e1u,
    0x013c3912u, 0x00fb2f4fu, 0x00c785efu, 0x009e7ca5u, 0x007de3ffu, 0x0063ff9bu,
    0x004f6e7eu, 0x003f1842u, 0x00321e32u, 0x0027cf63u, 0x001f9f4eu, 0x00191e54u,
    0x0013f3cbu, 0x000fd943u, 0x000c96ccu, 0x0009fff5u, 0x0007f173u, 0x00064f39u,
    0x00050305u, 0x0003fb23u, 0x00032987u, 0x00028308u, 0x0001fec7u, 0x000195b9u,
    0x00014247u, 0x0000cb58u, 0x0000a185u, 0x0000804du, 0x000065e9u, 0x000050f3u,
    0x0000404du, 0x00003313u, 0x00002892u, 0x0000203au, 0x00001999u, 0x00001455u,
    0x00001026u, 0x00000cd4u, 0x00000a30u, 0x00000818u
};

/* pow(10.0, arg * -0.1) * 65535.0, truncated: the ESC[..a argument is
 * masked to a byte before it gets here, so the domain is 0..255. */
uint32_t Volume_FromAtten(int32_t arg)
{
    return g_vol_of_atten[arg & 0xff];
}

/* log10(vol / 65535.0) * -10.0, truncated, then capped at 15.
 *
 * That is non-increasing in vol -- log10 rises, the negative scale falls,
 * and truncation preserves the order -- so each attenuation owns one
 * contiguous run of volumes and the table needs only where the runs end.
 * g_atten_bound[k - ATTEN_MIN] is the largest volume whose attenuation is
 * still at least k; the answer is the largest such k.  Volumes above 65535
 * give a negative attenuation, which the original also allows (truncation
 * rounds those toward zero, not down) and the corpus exercises.
 */
#define ATTEN_MIN (-48)
#define ATTEN_MAX 15

int32_t Volume_ToAtten(uint32_t vol)
{
    int32_t k = ATTEN_MAX;

    while (k > ATTEN_MIN && vol > g_atten_bound[k - ATTEN_MIN])
        k--;
    return k;
}
